import type { Metadata } from "next";
import { draftMode } from "next/headers";

import { geist, inter } from "~/styles/fonts";
import "~/styles/globals.css";
import { PreviewOverlay } from "~/components/preview-overlay";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isDraftMode = draftMode().isEnabled;

  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geist.variable} min-h-dvh overflow-x-hidden ${isDraftMode ? "bg-[#13141b]" : "bg-zinc-100"} font-sans text-black antialiased`}
      >
        <PreviewOverlay isDraftMode={isDraftMode}>{children}</PreviewOverlay>
      </body>
    </html>
  );
}
