import type { Metadata } from "next";
import { draftMode } from "next/headers";
import { VisualEditing } from "next-sanity";

import { geist, inter } from "~/styles/fonts";
import "~/styles/globals.css";
import { PreviewOverlay } from "~/components/preview-overlay";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isDraftMode = draftMode().isEnabled;

  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geist.variable} min-h-dvh overflow-x-hidden bg-zinc-100 font-sans text-black antialiased`}
      >
        <PreviewOverlay isDraftMode={isDraftMode}>
          {children}
          <VisualEditing />
        </PreviewOverlay>
      </body>
    </html>
  );
}
